package scraper

import (
	"time"

	"github.com/your-org/gtssp/internal/model"
	"github.com/your-org/gtssp/internal/util"
)

// Scraper defines how metrics are collected
type Scraper interface {
	Scrape() ([]model.Metric, error)
}

// DummyScraper is a simple scraper for initial testing
// This simulates metrics generated by applications or system agents
type DummyScraper struct{}

// NewDummyScraper creates a new scraper instance
func NewDummyScraper() *DummyScraper {
	return &DummyScraper{}
}

// Scrape generates sample time-series metrics
func (s *DummyScraper) Scrape() ([]model.Metric, error) {

	// Simulated raw metric generated by agent
	metric := model.Metric{
		Name:      "cpu_usage",
		Value:     0.65,
		Timestamp: time.Now(),
		Labels: map[string]string{
			"instance": "node-1",
			"job":      "demo-app",
		},
	}

	// Trace raw metric generation
	util.PrintStage("RAW METRIC (Generated by Agent)", metric)

	return []model.Metric{metric}, nil
}
